# docker-compose.yml

services:
  # Nginx
  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80" 
    volumes:
      - ./_Docker/Nginx/conf.d/:/etc/nginx/conf.d/
      - ./Backend/public:/var/www/html/backend/public
      # - ./Backend:/var/www/html/backend   # закомментировать
    depends_on:
      - laravel_php
    container_name: container-nginx
    restart: unless-stopped
    networks:
      - backend_network

  # Laravel
  laravel_php:
    image: adilkhan097/rubicon-backend:latest   # ← добавить эту строку
      # build: ...                                 # ← закомментировать или удалить
    volumes:
    # остальные поля (depends_on, container_name и т.д.) остаются
    # Убираем volume, который монтировал ./Backend — код теперь внутри образа
    #  - ./Backend:/var/www/html/backend:cached
    # Если вам нужно, чтобы некоторые папки (например, storage, public/uploads) сохраняли данные между перезапусками — оставьте volume только для них:
      - ./Backend/storage:/var/www/html/backend/storage
      - ./Backend/public/uploads:/var/www/html/backend/public/uploads
    depends_on:
      - laravel_db
    container_name: container-laravel
    restart: unless-stopped
    networks:
      - backend_network

  # Laravel + MariaDB
  laravel_db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - laravel_db_data:/var/lib/mysql
    networks:
      - backend_network

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: container-redis
    restart: unless-stopped
    networks:
      - backend_network

  # Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
    container_name: container-mosquitto
    restart: unless-stopped
    networks:
      - backend_network

volumes:
  laravel_db_data:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:

networks:
  backend_network:
    driver: bridge